name: Testing
on:
  pull_request:
    branches:
    - 'main'
    - 'dev'

jobs:
  Test-Job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Test
        run: python test.py
