name: Testing
on:
  pull_request:
    branches:
    - 'main'
    - 'dev'

jobs:
  Upstream-PR:
    strategy:
      matrix:
        subdir: ['lib']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Resolve diff
        id: status
        run: |
          git fetch ${{ github.base_ref }} && \
          git fetch ${{ github.head_ref }} && \
          echo ::set-output name=subdir_files_modified::$(git diff --dirstat=files,0 ${{ github.base_ref }}..${{ github.head_ref }} | grep " ${{ matrix.subdir }}/$" | wc -l)
      - name: Push branch
        if: steps.status.outputs.subdir_files_modified > 0
        id: subrepo
        run: |
          export GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }} && \
          git config --global user.name ${{ github.actor }} && \
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" && \
          git subrepo push ${{ matrix.subdir }} -b ${{ github.ref_name }}
      - name: Dispatch PR
        if: steps.status.outputs.subdir_files_modified > 0
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: juntaoluo/GithubAction-Subrepo
          event-type: update-pr
          client-payload: |
            {
              "base": "${{ github.base_ref }}"
              "branch": "${{ github.ref_name }}"
            }
