name: Subrepo Update
on:
  repository_dispatch:
    types: [update-subrepo-event]
jobs:
  Update_Subrepo:
    runs-on: ubuntu-latest
    steps:
      - name: Install Subrepo
        run: |
          git clone --depth=1 --branch=0.4.3 https://github.com/ingydotnet/git-subrepo.git /tmp/git-subrepo && \
          source /tmp/git-subrepo/.rc
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull update
        run: git subrepo pull lib -b ${{ github.event.client_payload.branch }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci/update-subrepo
          base: ${{ github.event.client_payload.branch }}
